name: Run test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Run bazel test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install bazel 
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel
      - name: run bazel test
        run: |
          touch WORKSPACE
          bazel --output_user_root=/tmp/output_build test ./