name: Run test
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Run bazel test
    runs-on: ubuntu-18.04
    steps:
      - name: Build site assets
        working-directory: ${{ github.workspace }}
        run: ls -la
      - name: show current WD
        run: |
          pwd
          ls -lah ../
          ls -lah ../../
          sudo find / -name tox.ini
      - name: apt-key add bazel 
        run: curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
      - name: add bazel repository
        run: echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - name: update repo and install bazel
        run: sudo apt update && sudo apt install bazel
      - name: run bazel test
        run:  bazel test --output_user_root=/tmp/output_build ...